# Generated by Django 3.1.1 on 2020-10-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='foto_carnet',
            field=models.ImageField(blank=True, null=True, upload_to='carnet'),
        ),
    ]
